.equiv v0,   $0

.equiv t0,   $1
.equiv t1,   $2
.equiv t2,   $3
.equiv t3,   $4
.equiv t4,   $5
.equiv t5,   $6
.equiv t6,   $7
.equiv t7,   $8

.equiv s0,   $9
.equiv s1,   $10
.equiv s2,   $11
.equiv s3,   $12
.equiv s4,   $13
.equiv s5,   $14
.equiv s6,   $15

.equiv fp,   $15

.equiv a0,   $16
.equiv a1,   $17
.equiv a2,   $18
.equiv a3,   $19
.equiv a4,   $20
.equiv a5,   $21

.equiv t8,   $22
.equiv t9,   $23
.equiv t10,  $24
.equiv t11,  $25

.equiv ra,   $26
.equiv pv,   $27  # procedure value
.equiv t12,  $27
.equiv at,   $28
.equiv gp,   $29
.equiv sp,   $30
.equiv zero, $31
